#!/usr/bin/env python

from multiprocessing import Process, Manager
import time

import obstacle_detection

def image_processing_loop(namespace):
    while True:
        if obstacle_detection.is_obstacle_detected():
            namespace.is_obstacle_detected = True
        print(namespace)
        time.sleep(0.3)

if __name__ == '__main__':
    with Manager() as manager:
        namespace = manager.Namespace()

        namespace.is_obstacle_detected = False

        p = Process(target=image_processing_loop, args=(namespace,))
        p.start()
        p.join()

        print(namespace)
